version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: akashjobanputra/exp-node-app
    depends_on:
      - mongo
    environment:
      - PORT=3000
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=akash
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    # volumes:
      # - redis-db

volumes:
  mongo-db:
